export const nameColumsHangHoa = {
  Nhom: 'Nhóm',
  TenNhom: 'Tên Nhóm',
  MaHang: 'Mã hàng',
  TenHang: 'Tên Hàng',
  DVTKho: 'Đơn Vị Tính (Kho)',
  TyLeQuyDoi: 'Tỷ Lệ Quy Đổi',
  DVTQuyDoi: 'Đơn Vị Tính (Quy Đổi)',
  DienGiaiDVTQuyDoi: 'Diển Giải DVT Quy Đổi',
  MaVach: 'Mã Vạch',
  DienGiaiHangHoa: 'Diển Giải Hàng Hóa',
  LapRap: 'Lắp Ráp',
  TonKho: 'Tồn Kho',
  GhiChu: 'Ghi Chú',
  GiaBanLe: 'Giá Bán Lẻ',
  CoThue: 'Có Thuế',
  TyLeThue: 'Tỷ lệ Thuế',
  BangGiaSi: 'Bảng Giá Sỉ',
  BangGiaSi_Min: 'Bảng Giá Sỉ (Min)',
  BangGiaSi_Max: 'Bảng Giá Sỉ (Max)',
  NguoiTao: 'Người Tạo',
  NgayTao: 'Ngày Tạo',
  NguoiSuaCuoi: 'Người Sửa Cuối',
  NgaySuaCuoi: 'Ngày Sửa Cuối',
}

export const nameColumsPhieuBanHang = {
  SoChungTu: 'Số Chứng Từ',
  NgayCTu: 'Ngày Chứng Từ',
  DaoHan: 'Đáo Hạn',
  MaDoiTuong: 'Mã Đối Tượng',
  TenDoiTuong: 'Tên Đối Tượng',
  DiaChi: 'Địa Chỉ',
  MaSoThue: 'Mã Số Thuế',
  MaKho: 'Mã Kho',
  ThongTinKho: 'Thông Tin Kho',
  GhiChu: 'Ghi Chú',
  TongMatHang: 'Tổng Mặt Hàng',
  TongSoLuong: 'Tổng Số Lượng',
  TongTienHang: 'Tổng Tiền Hàng',
  TongTienThue: 'Tổng Tiền Thuế',
  TongThanhTien: 'Tổng Thành Tiền',
  TyLeCKTT: 'TLCK Thanh Toán',
  TongTienCKTT: 'Tổng CKT Toán',
  TongTongCong: 'Tổng Cộng',
  TTTienMat: 'Tiền Mặt',
  PhieuThu: 'Phiếu Thu',
  NguoiTao: 'Người Tạo',
  NgayTao: 'Ngày Tạo',
  NguoiSuaCuoi: 'Người Sửa Cuối',
  NgaySuaCuoi: 'Ngày Sửa Cuối',
}

export const nameColumsPhieuMuaHang = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'DVT',
  SoLuong: 'Số lượng',
  DonGia: 'Đơn giá',
  TienHang: 'Tiền Hàng',
  TyLeThue: '% Thuế',
  TienThue: 'Tiền thuế',
  ThanhTien: 'Thành tiền',
}
export const nameColumsPhieuBanHangChiTiet = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'DVT',
  SoLuong: 'Số lượng',
  DonGia: 'Đơn giá',
  TienHang: 'Tiền Hàng',
  TyLeThue: '% Thuế',
  TienThue: 'Tiền thuế',
  ThanhTien: 'Thành tiền',
  TyLeCKTT: '% CK Thanh Toán',
  TienCKTT: 'Tiền CK.Thanh Toán',
  TongCong: 'Tổng',
}
